### ISSUE TITLE
Question about the pretrained models you provided

### ISSUE THREAD

**Issue by kasim0226** [lychenyoko/content-aware-gan-compression#11]
Thank you for sharinig tour pretrained models.

Could I know which version of pretrained models you provide?
Did you provide 'Ours-CA' in Table 4 in your paper?

**Comment by lychenyoko** [comment]
Yes, both 256px and 1024px compressed models in the repo are 'Ours-CA'.

**Comment by kasim0226** [comment]
Thank you for your reply.

Another question: 1024px compressed models in the repo is pruned 80% of channels of a full-size StyleGAN2?

**Comment by lychenyoko** [comment]
It is 70% pruned.

**Comment by kasim0226** [comment]
Thank you for your reply
