### ISSUE TITLE
A question about weight replication

### ISSUE THREAD

**Issue by TechSheng** [lychenyoko/content-aware-gan-compression#6]
Thank you for you good work very much！！！I have a small question 
https://github.com/lychenyoko/content-aware-gan-compression/blob/fa4193df630dd7b0e7fc52dd60669d8e1aefc39d/Util/mask_util.py#L119-L121
The weight in ToRGB includes conv.weight, conv.modulation.weight, conv.modulation.bias and conv.bias. There are four weight, why do weights copy only there of them?

**Comment by lychenyoko** [comment]
That's because conv.bias would also be of 3 dimension, since it is producing an RGB image. Therefore, you don't need to mask conv.bias.

**Comment by zuimeiyujianni** [comment]
Thank you for you reply 👍
